### PR TITLE
(API 15)Cache the JWT when the request contains the previous SAML

### PR DESCRIPTION
**Pull request by sreenicibc**
Issue #31, (API 15)Cache the JWT when the request contains the previous SAML

### CODE REVIEW

**Comment by miklish** [comment]
Ensure that (if a hash of the SAML is used to determine if it's been seen before) that an appropriately strong cryptographic hash is used.

**Comment by miklish** [comment]
I believe that a SHA-2 algorithm is required (not MD5).

**Comment by miklish** [comment]
Specifically we'll need to use 128-bit HMAC-SHA-2

**Comment by dguncb** [comment]
Hi MIke...yes it shold be updated to SHA256 but not HMAC. Any sort of MACs are not appropriate for this use case. They are for the JWT.

**Comment by miklish** [comment]
Makes sense in this case since the router is the only one that generates a hash of the SAML. But let's chat Monday as well

**Comment by sreenicibc** [comment]
Currently this request is on hold.

**Pull request closed without merging**
